config/routes.rb
Rails.application.routes.draw do
  resources :materia
  resources :estudiantes
  resources :profesors
  resources :semestres

end

app/models/estudiante.rb
class Estudiante < ActiveRecord::Base
end

app/models/materium.rb
class Materium < ActiveRecord::Base
end

app/models/profesor.rb
class Profesor < ActiveRecord::Base
end

app/models/semestre.rb
class Semestre < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController
  before_action :set_estudiante, only: [:show, :edit, :update, :destroy]

  # GET /estudiantes
  # GET /estudiantes.json
  def index
    @estudiantes = Estudiante.all
  end

  # GET /estudiantes/1
  # GET /estudiantes/1.json
  def show
  end

  # GET /estudiantes/new
  def new
    @estudiante = Estudiante.new
  end

  # GET /estudiantes/1/edit
  def edit
  end

  # POST /estudiantes
  # POST /estudiantes.json
  def create
    @estudiante = Estudiante.new(estudiante_params)

    respond_to do |format|
      if @estudiante.save
        format.html { redirect_to @estudiante, notice: 'Estudiante was successfully created.' }
        format.json { render :show, status: :created, location: @estudiante }
      else
        format.html { render :new }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estudiantes/1
  # PATCH/PUT /estudiantes/1.json
  def update
    respond_to do |format|
      if @estudiante.update(estudiante_params)
        format.html { redirect_to @estudiante, notice: 'Estudiante was successfully updated.' }
        format.json { render :show, status: :ok, location: @estudiante }
      else
        format.html { render :edit }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estudiantes/1
  # DELETE /estudiantes/1.json
  def destroy
    @estudiante.destroy
    respond_to do |format|
      format.html { redirect_to estudiantes_url, notice: 'Estudiante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estudiante
      @estudiante = Estudiante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estudiante_params
      params.require(:estudiante).permit(:nombre, :correo, :usuario, :password)
    end
end

app/controllers/materia_controller.rb
class MateriaController < ApplicationController
  before_action :set_materium, only: [:show, :edit, :update, :destroy]

  # GET /materia
  # GET /materia.json
  def index
    @materia = Materium.all
  end

  # GET /materia/1
  # GET /materia/1.json
  def show
  end

  # GET /materia/new
  def new
    @materium = Materium.new
  end

  # GET /materia/1/edit
  def edit
  end

  # POST /materia
  # POST /materia.json
  def create
    @materium = Materium.new(materium_params)

    respond_to do |format|
      if @materium.save
        format.html { redirect_to @materium, notice: 'Materium was successfully created.' }
        format.json { render :show, status: :created, location: @materium }
      else
        format.html { render :new }
        format.json { render json: @materium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materia/1
  # PATCH/PUT /materia/1.json
  def update
    respond_to do |format|
      if @materium.update(materium_params)
        format.html { redirect_to @materium, notice: 'Materium was successfully updated.' }
        format.json { render :show, status: :ok, location: @materium }
      else
        format.html { render :edit }
        format.json { render json: @materium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materia/1
  # DELETE /materia/1.json
  def destroy
    @materium.destroy
    respond_to do |format|
      format.html { redirect_to materia_url, notice: 'Materium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_materium
      @materium = Materium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def materium_params
      params.require(:materium).permit(:nom_materia)
    end
end

app/controllers/profesors_controller.rb
class ProfesorsController < ApplicationController
  before_action :set_profesor, only: [:show, :edit, :update, :destroy]

  # GET /profesors
  # GET /profesors.json
  def index
    @profesors = Profesor.all
  end

  # GET /profesors/1
  # GET /profesors/1.json
  def show
  end

  # GET /profesors/new
  def new
    @profesor = Profesor.new
  end

  # GET /profesors/1/edit
  def edit
  end

  # POST /profesors
  # POST /profesors.json
  def create
    @profesor = Profesor.new(profesor_params)

    respond_to do |format|
      if @profesor.save
        format.html { redirect_to @profesor, notice: 'Profesor was successfully created.' }
        format.json { render :show, status: :created, location: @profesor }
      else
        format.html { render :new }
        format.json { render json: @profesor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profesors/1
  # PATCH/PUT /profesors/1.json
  def update
    respond_to do |format|
      if @profesor.update(profesor_params)
        format.html { redirect_to @profesor, notice: 'Profesor was successfully updated.' }
        format.json { render :show, status: :ok, location: @profesor }
      else
        format.html { render :edit }
        format.json { render json: @profesor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profesors/1
  # DELETE /profesors/1.json
  def destroy
    @profesor.destroy
    respond_to do |format|
      format.html { redirect_to profesors_url, notice: 'Profesor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profesor
      @profesor = Profesor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profesor_params
      params.require(:profesor).permit(:nombre, :correo, :usuario, :password)
    end
end

app/controllers/semestres_controller.rb
class SemestresController < ApplicationController
  before_action :set_semestre, only: [:show, :edit, :update, :destroy]

  # GET /semestres
  # GET /semestres.json
  def index
    @semestres = Semestre.all
  end

  # GET /semestres/1
  # GET /semestres/1.json
  def show
  end

  # GET /semestres/new
  def new
    @semestre = Semestre.new
  end

  # GET /semestres/1/edit
  def edit
  end

  # POST /semestres
  # POST /semestres.json
  def create
    @semestre = Semestre.new(semestre_params)

    respond_to do |format|
      if @semestre.save
        format.html { redirect_to @semestre, notice: 'Semestre was successfully created.' }
        format.json { render :show, status: :created, location: @semestre }
      else
        format.html { render :new }
        format.json { render json: @semestre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /semestres/1
  # PATCH/PUT /semestres/1.json
  def update
    respond_to do |format|
      if @semestre.update(semestre_params)
        format.html { redirect_to @semestre, notice: 'Semestre was successfully updated.' }
        format.json { render :show, status: :ok, location: @semestre }
      else
        format.html { render :edit }
        format.json { render json: @semestre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /semestres/1
  # DELETE /semestres/1.json
  def destroy
    @semestre.destroy
    respond_to do |format|
      format.html { redirect_to semestres_url, notice: 'Semestre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_semestre
      @semestre = Semestre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def semestre_params
      params.require(:semestre).permit(:nombre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

app/helpers/materia_helper.rb
module MateriaHelper
end

app/helpers/profesors_helper.rb
module ProfesorsHelper
end

app/helpers/semestres_helper.rb
module SemestresHelper
end

app/views/estudiantes/_form.html.erb
<%= form_for(@estudiante) do |f| %>
  <% if @estudiante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estudiante.errors.count, "error") %> prohibited this estudiante from being saved:</h2>

      <ul>
      <% @estudiante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :correo %><br>
    <%= f.text_field :correo %>
  </div>
  <div class="field">
    <%= f.label :usuario %><br>
    <%= f.text_field :usuario %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estudiantes/edit.html.erb
<h1>Editing Estudiante</h1>

<%= render 'form' %>

<%= link_to 'Show', @estudiante %> |
<%= link_to 'Back', estudiantes_path %>

app/views/estudiantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Estudiantes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Correo</th>
      <th>Usuario</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estudiantes.each do |estudiante| %>
      <tr>
        <td><%= estudiante.nombre %></td>
        <td><%= estudiante.correo %></td>
        <td><%= estudiante.usuario %></td>
        <td><%= estudiante.password %></td>
        <td><%= link_to 'Show', estudiante %></td>
        <td><%= link_to 'Edit', edit_estudiante_path(estudiante) %></td>
        <td><%= link_to 'Destroy', estudiante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estudiante', new_estudiante_path %>

app/views/estudiantes/new.html.erb
<h1>New Estudiante</h1>

<%= render 'form' %>

<%= link_to 'Back', estudiantes_path %>

app/views/estudiantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @estudiante.nombre %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @estudiante.correo %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @estudiante.usuario %>
</p>

<p>
  <strong>Password:</strong>
  <%= @estudiante.password %>
</p>

<%= link_to 'Edit', edit_estudiante_path(@estudiante) %> |
<%= link_to 'Back', estudiantes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/materia/_form.html.erb
<%= form_for(@materium) do |f| %>
  <% if @materium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@materium.errors.count, "error") %> prohibited this materium from being saved:</h2>

      <ul>
      <% @materium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom_materia %><br>
    <%= f.text_field :nom_materia %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/materia/edit.html.erb
<h1>Editing Materium</h1>

<%= render 'form' %>

<%= link_to 'Show', @materium %> |
<%= link_to 'Back', materia_path %>

app/views/materia/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Materia</h1>

<table>
  <thead>
    <tr>
      <th>Nom materia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materia.each do |materium| %>
      <tr>
        <td><%= materium.nom_materia %></td>
        <td><%= link_to 'Show', materium %></td>
        <td><%= link_to 'Edit', edit_materium_path(materium) %></td>
        <td><%= link_to 'Destroy', materium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Materium', new_materium_path %>

app/views/materia/new.html.erb
<h1>New Materium</h1>

<%= render 'form' %>

<%= link_to 'Back', materia_path %>

app/views/materia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom materia:</strong>
  <%= @materium.nom_materia %>
</p>

<%= link_to 'Edit', edit_materium_path(@materium) %> |
<%= link_to 'Back', materia_path %>

app/views/profesors/_form.html.erb
<%= form_for(@profesor) do |f| %>
  <% if @profesor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profesor.errors.count, "error") %> prohibited this profesor from being saved:</h2>

      <ul>
      <% @profesor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :correo %><br>
    <%= f.text_field :correo %>
  </div>
  <div class="field">
    <%= f.label :usuario %><br>
    <%= f.text_field :usuario %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profesors/edit.html.erb
<h1>Editing Profesor</h1>

<%= render 'form' %>

<%= link_to 'Show', @profesor %> |
<%= link_to 'Back', profesors_path %>

app/views/profesors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profesors</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Correo</th>
      <th>Usuario</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profesors.each do |profesor| %>
      <tr>
        <td><%= profesor.nombre %></td>
        <td><%= profesor.correo %></td>
        <td><%= profesor.usuario %></td>
        <td><%= profesor.password %></td>
        <td><%= link_to 'Show', profesor %></td>
        <td><%= link_to 'Edit', edit_profesor_path(profesor) %></td>
        <td><%= link_to 'Destroy', profesor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profesor', new_profesor_path %>

app/views/profesors/new.html.erb
<h1>New Profesor</h1>

<%= render 'form' %>

<%= link_to 'Back', profesors_path %>

app/views/profesors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @profesor.nombre %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @profesor.correo %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @profesor.usuario %>
</p>

<p>
  <strong>Password:</strong>
  <%= @profesor.password %>
</p>

<%= link_to 'Edit', edit_profesor_path(@profesor) %> |
<%= link_to 'Back', profesors_path %>

app/views/semestres/_form.html.erb
<%= form_for(@semestre) do |f| %>
  <% if @semestre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@semestre.errors.count, "error") %> prohibited this semestre from being saved:</h2>

      <ul>
      <% @semestre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/semestres/edit.html.erb
<h1>Editing Semestre</h1>

<%= render 'form' %>

<%= link_to 'Show', @semestre %> |
<%= link_to 'Back', semestres_path %>

app/views/semestres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Semestres</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @semestres.each do |semestre| %>
      <tr>
        <td><%= semestre.nombre %></td>
        <td><%= link_to 'Show', semestre %></td>
        <td><%= link_to 'Edit', edit_semestre_path(semestre) %></td>
        <td><%= link_to 'Destroy', semestre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Semestre', new_semestre_path %>

app/views/semestres/new.html.erb
<h1>New Semestre</h1>

<%= render 'form' %>

<%= link_to 'Back', semestres_path %>

app/views/semestres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @semestre.nombre %>
</p>

<%= link_to 'Edit', edit_semestre_path(@semestre) %> |
<%= link_to 'Back', semestres_path %>